CREATE TABLE t_coffee
(
  id          BIGINT(20) NOT NULL AUTO_INCREMENT,
  name        VARCHAR(255) DEFAULT NULL,
  price       BIGINT(20) DEFAULT NULL,
  create_time TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;